control_node:
  ros__parameters:
    update_rate: 500
    cmd_name: gui/joint_states
    simulation: true
    sim_real_time: true
    hardware: hardwares::SimulationRobot
    sim_controller: controllers::RobotController
    controller: 
      - controllers::RobotController