control_node:
  ros__parameters:
    update_rate: 500
    cmd_name: gui/joint_states
    simulation: true
    sim_real_time: true
    publish_joint_state: true
    hardware: hardwares::SimulationRobot
    controllers: 
      - controllers::RobotController
    
    active_controller: 0