control_node:
  ros__parameters:
    update_rate: 500
    cmd_name: gui/joint_states
    simulation: true
    sim_real_time: true
    hardware_class: hardwares::SimulationHardware
    controller_class: controllers::MyController