control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: true
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::SimulationRobot
    controllers: 
      - controllers::TorqueController
      - controllers::ForwardController
      - controllers::RealtimeTestController

SimulationRobot:
  ros__parameters:
    end_effector: ""
    joint_command_interface:
      - position
      - velocity
      - torque
    joint_state_interface:
      - position
      - velocity
      - torque
