control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::SimulationRobot
    parameters: "parameters.yaml"
    controllers: 
      - controllers::JointMotionController
      - controllers::CartesianMotionController
      - controllers::CartesianTrajectoryController
      - controllers::ForwardController
      - controllers::RealtimeTestController
    default_controller: ""

SimulationRobot:
  ros__parameters:
    end_effector: ""
    joint_command_interface:
      - position
      - velocity
      - torque
    joint_state_interface:
      - position
      - velocity
      - torque
    init_joint_pose: [.0, -0.962, 1.730, -3.842, -1.843, 0.0] #[.0, .0, .0, .0, .0, .0] #
    command_interface: [mode, pose]
    command_length: [1, 6] # mode = 0: cartesian, 1: joint position 2: joint velocity 3: joint torque
    command_type: [int, double]
    # sensors: [ft_sensor]
    # ft_sensor: hardwares::FTDummySensor

# ft_sensor:
#   ros__parameters:
#     state_interface: [force]
#     state_length: [6]
#     sensor_ip: 192.168.110.101
#     sensor_port: 4008


ForwardController:
  ros__parameters:
    cmd_name: "position"
