control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::SimulationRobot
    controllers: 
      - controllers::DummyController
      
SimulationRobot:
  ros__parameters:
    end_effector: ""
    command_interface:
      - position
      - velocity
      - torque
    state_interface:
      - position
      - velocity
    sensors: [ft_sensor]
    ft_sensor: hardwares::FTDummySensor

ft_sensor:
  ros__parameters:
    state_interface: force
    length: 6

