control_node:
  ros__parameters:
    update_rate: 1000
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::FC3Robot
    controllers: 
      - controllers::TorqueController
      - controllers::RCMController
      - controllers::JointImpedanceController
      - controllers::CartesianImpedancePDController
      - controllers::CartesianImpedancePDPlusController
      - controllers::VirtualFixturePlaneController
      - controllers::VirtualFixtureLineController

FC3Robot:
  ros__parameters:
    robot_ip: 192.168.1.101
    end_effector: ""
    # joint interface:
    joint_command_interface:
      - torque 
    joint_state_interface:
      - position
      - velocity
      - torque
    # other interface:
    command_interface: [mode, pose]
    command_length: [2, 6]
    command_type: [int, double]
    state_interface: [T, c, g, external_torque, success, m]
    state_length: [16, 7, 7, 7, 1, 49]
    state_type: [double, double, double, double, double, double]

JointImpedanceController:
  ros__parameters:
    K: [60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0]
    B: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

CartesianImpedancePDController:
  ros__parameters:
    Kx: [400.0, 400.0, 400.0, 80.0, 80.0, 80.0]
    # Kx: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    Bx: [40.0, 40.0, 40.0, 17.0, 17.0, 17.0]
    Kn: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    # Kn: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    Bn: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]

CartesianImpedancePDPlusController:
  ros__parameters:
    Kx: [20.0, 20.0, 20.0, 80.0, 80.0, 80.0]
    Bx: [8.0, 8.0, 8.0, 17.0, 17.0, 17.0]
    Kn: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    Bn: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]

VirtualFixturePlaneController:
  ros__parameters:
    Ku: [2000.0]
    Bu: [50.0]
    Kn: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    Bn: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
    Y: 1.0

VirtualFixtureLineController:
  ros__parameters:
    Ku: [2000.0, 2000.0]
    Bu: [50.0, 50.0]
    Kn: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    Bn: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
    Y: 1.0

VirtualFixtureGeneralController:
  ros__parameters:
    Ku: [2000.0, 2000.0]
    Bu: [50.0, 50.0]
    Kn: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    Bn: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
    Y: 1.0