control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::URRobot
    controllers: 
      - controllers::ForceDragController
      - controllers::ForceDragDevController
      - controllers::AdmittanceController
      - controllers::JointMotionController
      - controllers::CartesianMotionController

ForceDragController:
  ros__parameters:
    mass: 4.31433
    cog: [0.0023108, 0.00155013, 0.0463919]
    offset: [0.567867, 2.65463, 1.75407, 0.0349296, -0.0622864, -0.0820951]
    sensor_pose: [.0, .0, .0475, .0, .0, .0]
    tcp_pose: [.0, .0, .05, .0, .0, .0]
    M: [0.05, 0.05, 0.05, 0.5, 0.5, 0.5]
    B: [5., 5., 5., 50., 50., 50.]

ForceDragDevController:
  ros__parameters:
    mass: 4.31433
    cog: [0.0023108, 0.00155013, 0.0463919]
    offset: [0.567867, 2.65463, 1.75407, 0.0349296, -0.0622864, -0.0820951]
    sensor_pose: [.0, .0, .0475, .0, .0, .0]
    tcp_pose: [.0, .0, .0, .0, .0, .0]

AdmittanceController:
  ros__parameters:
    mass: 4.31433
    cog: [0.0023108, 0.00155013, 0.0463919]
    offset: [0.567867, 2.65463, 1.75407, 0.0349296, -0.0622864, -0.0820951]
    sensor_pose: [.0, .0, .0475, .0, .0, .0]
    tcp_pose: [.0, .0, .0, .0, .0, .0]

JointMotionController:
  ros__parameters:
    cmd_name: "position"

CartesianMotionController:
  ros__parameters:
    cmd_name: "pose"

URRobot:
  ros__parameters:
    robot_ip: 192.168.124.201
    end_effector: ""
    # joint interface:
    joint_command_interface:
      - position # servoJ
      - velocity # speedJ
    joint_state_interface:
      - position
      - velocity
      - acceleration
    # other interface:
    command_interface: [mode, pose]
    command_length: [2, 6]
    command_type: [int, double]
    state_interface: [io, pose]
    state_length: [6, 6]
    state_type: [bool, double]
    # sensors:
    sensors: [ft_sensor]
    ft_sensor: hardwares::FTATISensor

ft_sensor:
  ros__parameters:
    sensor_ip: 192.168.124.12
    state_interface: [force]
    state_length: [6]    

