control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::URRobot
    controllers: 
      - controllers::ForceDragController
      
ForceDragController:
  ros__parameters:
    mass: 4.69166
    cog: [0.0188323, 0.00468353, 0.0435661]
    offset: [0.750243, 3.435, 1.0287, -0.067, -0.148, -0.086]
    pose: [.0, .0, .0475, .0, .0, .0]

URRobot:
  ros__parameters:
    robot_ip: 192.168.31.201
    end_effector: ""
    joint_command_interface:
      - position
      - velocity
    joint_state_interface:
      - position
      - velocity
      - acceleration
    # command_interface: []
    # command_length: []
    state_interface: [io]
    state_length: [6]
    state_type: [int]
    sensors: [ft_sensor]
    ft_sensor: hardwares::FTATISensor

ft_sensor:
  ros__parameters:
    sensor_ip: 192.168.124.12
    state_interface: force
    length: 6      

