control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    hardware: hardwares::SimulationRobot
    controllers: 
      - controllers::ForwardController
      - controllers::RealtimeTestController