control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::URRobot
    controllers: 
      - controllers::ForceDragController
      - controllers::ForceDragDevController
      - controllers::AdmittanceController
      
ForceDragController:
  ros__parameters:
    mass: 7.54128
    cog: [0.0297184, -0.00390314, 0.0543826]
    offset: [0.949434, 2.35846, -0.68032, 0.0282969, -0.0161999, -0.0863016]
    pose: [.0, .0, .0475, .0, .0, .0]

ForceDragDevController:
  ros__parameters:
    mass: 7.54128
    cog: [0.0297184, -0.00390314, 0.0543826]
    offset: [0.949434, 2.35846, -0.68032, 0.0282969, -0.0161999, -0.0863016]
    pose: [.0, .0, .0475, .0, .0, .0]

AdmittanceController:
  ros__parameters:
    mass: 7.54128
    cog: [0.0297184, -0.00390314, 0.0543826]
    offset: [0.949434, 2.35846, -0.68032, 0.0282969, -0.0161999, -0.0863016]
    pose: [.0, .0, .0475, .0, .0, .0]

URRobot:
  ros__parameters:
    robot_ip: 192.168.124.201
    end_effector: ""
    # joint interface:
    joint_command_interface:
      - position # servoJ
      - velocity # speedJ
    joint_state_interface:
      - position
      - velocity
      - acceleration
    # other interface:
    command_interface: [mode, pose]
    command_length: [1, 6]
    command_type: [int, double]
    state_interface: [io, pose]
    state_length: [6, 6]
    state_type: [bool, double]
    # sensors:
    sensors: [ft_sensor]
    ft_sensor: hardwares::FTATISensor

ft_sensor:
  ros__parameters:
    sensor_ip: 192.168.124.12
    state_interface: [force]
    state_length: [6]    

