control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::URRobot
    controllers: 
      - controllers::ForceDragController
      
URRobot:
  ros__parameters:
    robot_ip: 192.168.31.201
    sensors:
      - hardwares::FTATISensor

FTATISensor:
  ros__parameters:
    sensor_ip: 192.168.124.12
    mass: 0.967923
    cog: [0.00119462, -0.00020578, -0.0129575]
    offset: [0.303933, 3.52971, 0.327006, 0.0194561, -0.092082, -0.0818083]
    pose: [.0, .0, .0475, .0, .0, .0]
